Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -15,7 +15,8 @@ jobs:
       contents: read
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout Repository
+      uses: actions/checkout@v4
 
     - name: Set up JDK 21
       uses: actions/setup-java@v4
@@ -31,8 +32,11 @@ jobs:
       with:
         gradle-version: 8.10
 
-    - name: Build with Gradle (without Wrapper)
-      run: gradle build --stacktrace
+    - name: Build and Run Tests
+      run: gradle build test --stacktrace
+
+    - name: Debug:Check test reports
+      run: ls -R build/reports/tests/ || echo "Test reports directory not found!"
 
     - name: Upload Test Report
       uses: actions/upload-artifact@v4
@@ -43,4 +47,4 @@ jobs:
     - name: Display Test Report in Summary
       run: |
         echo "## Test Results" | tee -a $GITHUB_STEP_SUMMARY
-        cat build/reports/tests/test/index.html | tee -a $GITHUB_STEP_SUMMARY || echo "Test report not found."
+        if [ -f build/re
